
const $=(s,c=document)=>c.querySelector(s); const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const nav=$('.nav'); if(nav){const sync=()=>nav.classList.toggle('light',scrollY>40 || !document.body.classList.contains('home')); sync(); addEventListener('scroll',sync)}
const menu=$('.menu-btn'), panel=$('.mobile-panel'); if(menu&&panel){menu.onclick=()=>panel.classList.toggle('open'); $$('.mobile-panel a').forEach(a=>a.onclick=()=>panel.classList.remove('open'))}
const slides=$$('.slide'), dots=$$('.dot'); if(slides.length){let i=0,t;const go=n=>{slides[i].classList.remove('active');dots[i]?.classList.remove('active');i=n;slides[i].classList.add('active');dots[i]?.classList.add('active')}; const start=()=>{clearInterval(t);t=setInterval(()=>go((i+1)%slides.length),6500)};dots.forEach((d,n)=>d.onclick=()=>{go(n);start()});start()}
const countries=Object.keys(Intl.DisplayNames?new Intl.DisplayNames(['en'],{type:'region'}):{});
const countryCodes=['AF','AL','DZ','AD','AO','AG','AR','AM','AU','AT','AZ','BS','BH','BD','BB','BY','BE','BZ','BJ','BT','BO','BA','BW','BR','BN','BG','BF','BI','CV','KH','CM','CA','CF','TD','CL','CN','CO','KM','CG','CR','CI','HR','CU','CY','CZ','DK','DJ','DM','DO','EC','EG','SV','GQ','ER','EE','SZ','ET','FJ','FI','FR','GA','GM','GE','DE','GH','GR','GD','GT','GN','GW','GY','HT','HN','HU','IS','IN','ID','IR','IQ','IE','IL','IT','JM','JP','JO','KZ','KE','KI','KP','KR','KW','KG','LA','LV','LB','LS','LR','LY','LI','LT','LU','MG','MW','MY','MV','ML','MT','MH','MR','MU','MX','FM','MD','MC','MN','ME','MA','MZ','MM','NA','NR','NP','NL','NZ','NI','NE','NG','MK','NO','OM','PK','PW','PA','PG','PY','PE','PH','PL','PT','QA','RO','RU','RW','KN','LC','VC','WS','SM','ST','SA','SN','RS','SC','SL','SG','SK','SI','SB','SO','ZA','ES','LK','SD','SR','SE','CH','SY','TJ','TZ','TH','TL','TG','TO','TT','TN','TR','TM','TV','UG','UA','AE','GB','US','UY','UZ','VU','VE','VN','YE','ZM','ZW'];
$$('[data-country-select]').forEach(sel=>{countryCodes.forEach(c=>{const o=document.createElement('option');o.value=new Intl.DisplayNames(['en'],{type:'region'}).of(c);o.textContent=o.value;sel.append(o)})});
$$('select[name="role"]').forEach(sel=>sel.onchange=()=>{const other=sel.closest('form').querySelector('.other-role');other?.classList.toggle('hidden',sel.value!=='Other — Please Specify')});
const pricing={India:{currency:'₹',architectural:'₹6,000+',interior:'₹3,500+',animation:'Custom quote',marketing:'Custom quote',file:'Indian Pricing guide - Dezivia Atelier.pdf'},Australia:{currency:'A$',architectural:'A$450+',interior:'A$300+',animation:'Custom quote',marketing:'Custom quote',file:'Australian Pricing guide - Dezivia Atelier.pdf'},USA:{currency:'US$',architectural:'US$450+',interior:'US$300+',animation:'Custom quote',marketing:'Custom quote',file:'USA Pricing guide - Dezivia Atelier.pdf'},Canada:{currency:'C$',architectural:'C$450+',interior:'C$300+',animation:'Custom quote',marketing:'Custom quote',file:'Canada Pricing guide - Dezivia Atelier.pdf'},Philippines:{currency:'₱',architectural:'₱6,000+',interior:'₱3,000+',animation:'₱10,000+',marketing:'Custom quote',file:'Philippines Pricing guide - Dezivia Atelier.pdf'},Europe:{currency:'€',architectural:'€500+',interior:'€350+',animation:'Custom quote',marketing:'Custom quote',file:'European Pricing guide - Dezivia Atelier.pdf'},'Middle East':{currency:'US$',architectural:'US$700+',interior:'US$450+',animation:'Custom quote',marketing:'Custom quote',file:'Middle East Pricing guide - Dezivia Atelier.pdf'}};
const regionFor=country=>{if(['IN'].includes(country))return'India';if(['AU'].includes(country))return'Australia';if(['US'].includes(country))return'USA';if(['CA'].includes(country))return'Canada';if(['PH'].includes(country))return'Philippines';if(['AE','SA','QA','KW','OM','BH'].includes(country))return'Middle East';if(['DE','FR','NL','BE','AT','ES','IT','IE','PT','GB','CH','NO','SE','DK','PL'].includes(country))return'Europe';return'India'};
const regionSelect=$('#regionSelect');function renderPricing(r){const d=pricing[r]||pricing.India;$$('[data-price]').forEach(e=>e.textContent=d[e.dataset.price]);const link=$('#pricingDownload');if(link){link.href='assets/pricing/'+d.file;link.textContent='DOWNLOAD '+r.toUpperCase()+' PRICING GUIDE ↓'}if(regionSelect)regionSelect.value=r}
if(regionSelect){Object.keys(pricing).forEach(r=>{const o=document.createElement('option');o.value=r;o.textContent=r;regionSelect.append(o)});regionSelect.onchange=()=>renderPricing(regionSelect.value);let code='';try{code=Intl.DateTimeFormat().resolvedOptions().locale.match(/-([A-Z]{2})$/)?.[1]||''}catch(e){}renderPricing(regionFor(code))}
async function submitForm(form){const btn=$('button[type="submit"]',form),status=$('.status',form);btn.disabled=true;btn.textContent='SENDING…';try{const data=Object.fromEntries(new FormData(form).entries());const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await res.json();if(!res.ok)throw Error(out.error||'Something went wrong');status.innerHTML=out.message||"<strong>THANK YOU!</strong><br>We've received your message. We'll get back to you as soon as possible through <strong>contact@dezivia.in</strong>.";status.classList.add('show');form.reset()}catch(err){status.textContent='We could not send your message right now. Please email Contact@dezivia.in.';status.classList.add('show')}finally{btn.disabled=false;btn.textContent=form.dataset.join?'JOIN DEZIVIA →':'SEND MESSAGE →'}}
$$('form[data-api-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();submitForm(f)}));
